# Generated by Django 5.2.3 on 2025-06-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_company_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
