# Generated by Django 5.2.3 on 2025-06-27 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_testassignment_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_app.test'),
        ),
    ]
