# Generated by Django 5.2.3 on 2025-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_notification_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
