# Generated by Django 5.2.3 on 2025-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0005_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='manual_points',
            field=models.PositiveIntegerField(default=0, help_text='Ручные баллы для открытых вопросов'),
        ),
    ]
