# Generated by Django 5.2.3 on 2025-09-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0006_answer_manual_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='test',
            name='position',
            field=models.CharField(blank=True, help_text='Должность для теста (можно выбрать или ввести вручную)', max_length=100, null=True),
        ),
    ]
