# Generated by Django 5.2.3 on 2025-09-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0007_remove_test_time_limit_test_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, default=None, help_text='Должность соискателя', max_length=100, null=True),
        ),
    ]
